// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-clients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-clients.ts
var list_clients_default = defineTool({
  name: "list_clients",
  title: "Listar clientes",
  description: "Lista los clientes de la cl\xEDnica, con b\xFAsqueda opcional por nombre, email o tel\xE9fono.",
  inputSchema: {
    search: z.string().optional().describe("Texto a buscar en nombre, email o tel\xE9fono."),
    limit: z.number().int().optional().describe("M\xE1ximo de clientes a devolver (por defecto 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clients").select("id, full_name, email, phone, total_visits, last_visit_at, lifetime_value").order("last_visit_at", { ascending: false, nullsFirst: false }).limit(max);
    if (search?.trim()) {
      const term = `%${search.trim()}%`;
      query = query.or(`full_name.ilike.${term},email.ilike.${term},phone.ilike.${term}`);
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { clients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-client.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_client_default = defineTool2({
  name: "get_client",
  title: "Detalle de cliente",
  description: "Devuelve el detalle de un cliente: datos de contacto, paquetes contratados y pr\xF3ximas citas.",
  inputSchema: { client_id: z2.string().describe("UUID del cliente.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ client_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: client, error } = await supabase.from("clients").select("id, full_name, email, phone, notes, total_visits, first_visit_at, last_visit_at, lifetime_value").eq("id", client_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!client) return { content: [{ type: "text", text: "Cliente no encontrado" }], isError: true };
    const [{ data: packages }, { data: appointments }] = await Promise.all([
      supabase.from("packages").select("id, name, total_sessions, sessions_used, price_paid, price_per_session, status, expires_at").eq("client_id", client_id),
      supabase.from("appointments").select("id, scheduled_at, status, type, staff_id, package_id, price").eq("client_id", client_id).order("scheduled_at", { ascending: false }).limit(20)
    ]);
    const payload = { client, packages: packages ?? [], appointments: appointments ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "Listar citas",
  description: "Lista las citas de la agenda en un rango de fechas, opcionalmente filtradas por estado o por profesional.",
  inputSchema: {
    from: z3.string().optional().describe("Fecha inicial ISO (YYYY-MM-DD). Por defecto hoy."),
    to: z3.string().optional().describe("Fecha final ISO (YYYY-MM-DD). Por defecto 7 d\xEDas despu\xE9s."),
    status: z3.string().optional().describe("Estado: scheduled, done, cancelled, no_show, pending."),
    staff_id: z3.string().optional().describe("UUID del profesional.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, staff_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const start = from ? new Date(from) : /* @__PURE__ */ new Date();
    const end = to ? new Date(to) : new Date(start.getTime() + 7 * 864e5);
    if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
      return { content: [{ type: "text", text: "Fechas inv\xE1lidas" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("appointments").select("id, client_id, staff_id, package_id, service_id, scheduled_at, duration_minutes, status, type, price, notes").gte("scheduled_at", start.toISOString()).lte("scheduled_at", end.toISOString()).order("scheduled_at", { ascending: true }).limit(200);
    if (status) query = query.eq("status", status);
    if (staff_id) query = query.eq("staff_id", staff_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var create_appointment_default = defineTool4({
  name: "create_appointment",
  title: "Agendar cita",
  description: "Crea una nueva cita agendada para un cliente con un profesional en una fecha y hora determinadas.",
  inputSchema: {
    client_id: z4.string().describe("UUID del cliente."),
    staff_id: z4.string().describe("UUID del profesional que atender\xE1."),
    scheduled_at: z4.string().describe("Fecha y hora de inicio en ISO 8601."),
    duration_minutes: z4.number().int().optional().describe("Duraci\xF3n en minutos (por defecto 60)."),
    type: z4.string().optional().describe("Tipo: rehabilitation, prehabilitation, recovery, medical_diagnosis, physio_diagnosis."),
    package_id: z4.string().optional().describe("UUID del paquete al que se descuenta la sesi\xF3n."),
    notes: z4.string().optional().describe("Notas de la cita.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const start = new Date(input.scheduled_at);
    if (Number.isNaN(start.getTime())) {
      return { content: [{ type: "text", text: "scheduled_at inv\xE1lido" }], isError: true };
    }
    const duration = Math.min(Math.max(input.duration_minutes ?? 60, 15), 240);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("appointments").insert({
      client_id: input.client_id,
      staff_id: input.staff_id,
      scheduled_at: start.toISOString(),
      start_time: start.toISOString(),
      end_time: new Date(start.getTime() + duration * 6e4).toISOString(),
      duration_minutes: duration,
      status: "scheduled",
      type: input.type ?? null,
      package_id: input.package_id ?? null,
      notes: input.notes ?? null
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { appointment: data }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_services_default = defineTool5({
  name: "list_services",
  title: "Cat\xE1logo de servicios",
  description: "Lista el cat\xE1logo de servicios/paquetes con su programa, n\xFAmero de sesiones y precios.",
  inputSchema: {
    program: z5.string().optional().describe("Filtrar por programa, p. ej. Rehabilitaci\xF3n o Recovery."),
    only_active: z5.boolean().optional().describe("Solo servicios activos (por defecto true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ program, only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("services").select("id, name, program, category, sessions, price, price_per_session, duration_minutes, active").order("program", { ascending: true });
    if (only_active !== false) query = query.eq("active", true);
    if (program) query = query.eq("program", program);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-staff.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var list_staff_default = defineTool6({
  name: "list_staff",
  title: "Listar equipo",
  description: "Lista los profesionales del equipo con su rol, tipo y horario de disponibilidad.",
  inputSchema: {
    only_active: z6.boolean().optional().describe("Solo profesionales activos (por defecto true).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("staff").select("id, name, role, type, is_active, schedule_days, schedule_start, schedule_end").order("name", { ascending: true });
    if (only_active !== false) query = query.eq("is_active", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { staff: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/revenue-summary.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z7 } from "npm:zod@^4.4.3";
var STANDALONE_PRICE = {
  medical_diagnosis: 120,
  physio_diagnosis: 100,
  rehabilitation: 90,
  prehabilitation: 90,
  recovery: 70
};
var revenue_summary_default = defineTool7({
  name: "revenue_summary",
  title: "Resumen de ingresos",
  description: "Resume los ingresos de un periodo: cobrado (pagos registrados) y devengado (sesiones realizadas valorizadas).",
  inputSchema: {
    from: z7.string().describe("Fecha inicial ISO (YYYY-MM-DD)."),
    to: z7.string().describe("Fecha final ISO (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const start = new Date(from);
    const end = new Date(to);
    if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) {
      return { content: [{ type: "text", text: "Fechas inv\xE1lidas" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const [{ data: payments, error: payErr }, { data: appointments, error: apptErr }] = await Promise.all([
      supabase.from("payments").select("amount, paid_at, status").gte("paid_at", start.toISOString()).lte("paid_at", end.toISOString()),
      supabase.from("appointments").select("id, scheduled_at, type, price, package_id").eq("status", "done").gte("scheduled_at", start.toISOString()).lte("scheduled_at", end.toISOString())
    ]);
    if (payErr) return { content: [{ type: "text", text: payErr.message }], isError: true };
    if (apptErr) return { content: [{ type: "text", text: apptErr.message }], isError: true };
    const packageIds = [...new Set((appointments ?? []).map((a) => a.package_id).filter(Boolean))];
    let packagePrices = {};
    if (packageIds.length) {
      const { data: pkgs } = await supabase.from("packages").select("id, price_per_session, total_paid, total_sessions").in("id", packageIds);
      packagePrices = Object.fromEntries(
        (pkgs ?? []).map((p) => [
          p.id,
          Number(p.price_per_session) || (p.total_sessions ? Number(p.total_paid ?? 0) / Number(p.total_sessions) : 0)
        ])
      );
    }
    const collected = (payments ?? []).reduce((sum, p) => sum + Number(p.amount ?? 0), 0);
    const accrued = (appointments ?? []).reduce((sum, a) => {
      const fromPackage = a.package_id ? packagePrices[a.package_id] ?? 0 : 0;
      const value = fromPackage || Number(a.price ?? 0) || STANDALONE_PRICE[a.type ?? ""] || 0;
      return sum + value;
    }, 0);
    const payload = {
      from: start.toISOString(),
      to: end.toISOString(),
      collected: Math.round(collected * 100) / 100,
      accrued: Math.round(accrued * 100) / 100,
      sessions_done: appointments?.length ?? 0,
      payments_count: payments?.length ?? 0,
      currency: "PEN"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lccdqxhyasahghlmisct";
var mcp_default = defineMcp({
  name: "movebetter-v1",
  title: "movebetter.v1",
  version: "0.1.0",
  instructions: "Herramientas del CRM de la cl\xEDnica de fisioterapia Move Better: consultar clientes, agenda, cat\xE1logo de servicios, equipo e ingresos (cobrado y devengado), y agendar nuevas citas. Todo opera con la identidad del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_clients_default,
    get_client_default,
    list_appointments_default,
    create_appointment_default,
    list_services_default,
    list_staff_default,
    revenue_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
