// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lccdqxhyasahghlmisct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjY2RxeGh5YXNhaGdobG1pc2N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4ODY4NTQsImV4cCI6MjA5NDQ2Mjg1NH0._o446N1WrQpaq_LFVHz_JLTaGuoKVXsAqp1dKfXMtH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});